var DaViSettings = {

	dayStart : 8,
	dayEnd : 19,
	days : ["Monday","Tuesday","Wednesday","Thursday","Friday"],
	workdays : ["Monday","Tuesday","Wednesday","Thursday","Friday"],
	timeTableDivId : "tableDiv",
	timeTableId : "svgTable",
	courseListId : "courses",
	cellCourseRow : "card",
	titlesInfo: "titlesInfo",
	cellDefaultClass : "timetableCell",
	cellCourseClass : "timetableCellCourse",
	cellExerciseClass : "timetableCellExercise",
	timetableRowClass : "timetableRow",
	courseListRowClass : "courseListRow",
	rescaleTableButtonId : "rescaleTableButton",
	tableGroupId : "tableGroup",
	cellDefaultColor : "#f6f6f6",
	cellTextClass : "cellTextClass",
	cellTextId : "cellTextId",
	cellBackId : "cellBackId",
	cellGroupId : "cellGroupId",
	cellId : "courseCell",
	cellDivId : "courseCellDiv",
	cellAId : "courseCellA",
	cellFontVerySmall : "0.2em",
	cellFontDefault : "1em",
	cellTextVis : "cellTextVis",
	cellVisGroupsCount : 3,
	cellTitleDiv : "cellTitleDiv",
	cellCoursesDiv : "cellCoursesDiv",
	cellCodeDiv : "cellCodeDiv",
	cellRoomDiv : "cellRoomDiv",
	cellNameDiv : "cellNameDiv",
	defaultDelay : 200,
	shortNoticeableDelay : 500,
	dayshoursDivOffset : new Vec(30,30),
	tableDimBig : new Vec(775,480),
	tableDimSmall : new Vec(775,480),
	cellBigScale : new Vec(1.5,1.5),
	cellMargin : new Vec(2,2),
	tableTextCount  : 100,
	tempTextId : "tempTextId",
	conflictColor: "#E54535",
	cellColorMap : {0:"#9ED4E0",1:"#D1E874",2:"#FDFF87",98:'#67706F',3:'#67706F',conflict:"#E54535"},
	tooltipClass : "tooltip",
	tooltipTextClass : "tooltiptext",
	chartClass : "chart",
	dashPatternPrefix : "dashPattern",
	detailDiv : "detailDiv",
	cellTitleTextClass : "cellTitleTextClass",
	roomLinkTextClass : "roomLinkTextClass",
	epflPlanQuerry :"https://plan.epfl.ch/?lang=fr&room=",
	dashdPatternDims : new Vec(30,30),
	dashedLineAngle : 45,
	shadowDarkness : 0.3,
	maxDisplayedSpe : 4,
	userSection : "IN",
	textOff : new Vec(3,3),
	spePlotId : "insightfullPlot1",
	spePlotRectO : new Vec(0.1,0.7),
	spePlotBarMargin : 0.03,
	peBarMaxWidth : 0.5,
	HoverTimout : 200,
	startArmLenght :0.65,
	activities : [0,1,2,98,"conflict"]


}
