var DaViSettings = {

	dayStart : 8,
	dayEnd : 19,
	days : ["Monday","Tuesday","Wensday","Thursday","Friday","Saturday"],
	timeTableDivId : "tableDiv",
	timeTableId : "svgTable",
	courseListId : "courses",
	cellCourseRow : "card",
	titlesInfo: "titlesInfo",
	cellDefaultClass : "timetableCell",
	cellCourseClass : "timetableCellCourse",
	cellExerciseClass : "timetableCellExercise",
	timetableRowClass : "timetableRow",
	courseListRowClass : "courseListRow",
	rescaleTableButtonId : "rescaleTableButton",
	tableGroupId : "tableGroup",
	cellDefaultColor : "#f6f6f6",
	cellTextClass : "cellTextClass",
	cellTextId : "cellTextId",
	cellBackId : "cellBackId",
	cellGroupId : "cellGroupId",
	cellId : "courseCell",
	cellDivId : "courseCellDiv",
	cellAId : "courseCellA",
	cellFontVerySmall : "0.2em",
	cellFontDefault : "1em",
	cellTextVis : "cellTextVis",
	cellVisGroupsCount : 3,
	cellTitleDiv : "cellTitleDiv",
	cellCoursesDiv : "cellCoursesDiv",
	cellCodeDiv : "cellCodeDiv",
	cellRoomDiv : "cellRoomDiv",
	cellNameDiv : "cellNameDiv",
	defaultDelay : 200,
	shortNoticeableDelay : 500,
	dayshoursDivOffset : new Vec(50,50),
	tableDimBig : new Vec(825,480),
	tableDimSmall : new Vec(825,480),
	cellBigScale : new Vec(1.5,1.5),
	cellMargin : new Vec(2,2),
	tableTextCount  : 100,
	tempTextId : "tempTextId",
	conflictColor: "#e81200",
	cellColorMap : {0:"#9ED4E0",1:"#D1E874",2:"#FDFF8798",98:'#67706F',3:'#67706F'},
	tooltipClass : "tooltip",
	tooltipTextClass : "tooltiptext",
	chartClass : "chart",
	dashPatternPrefix : "dashPattern",
	detailDiv : "detailDiv",
	cellTitleTextClass : "cellTitleTextClass",
	roomLinkTextClass : "roomLinkTextClass",
	epflPlanQuerry :"https://plan.epfl.ch/?lang=fr&room=",
	dashdPatternDims : new Vec(30,30),
	dashedLineAngle : 45,
	shadowDarkness : 0.3

}
